import { ReactNode, useEffect } from "react";

const updated = "2 de setembro de 2026";

export function LegalPage({ kind }: { kind: "privacy" | "terms" }) {
  const privacy = kind === "privacy";
  useEffect(() => { document.title = `${privacy ? "Política de Privacidade" : "Termos de Uso"} | FIXAR`; const description = document.querySelector('meta[name="description"]') ?? document.head.appendChild(document.createElement("meta")); description.setAttribute("name", "description"); description.setAttribute("content", privacy ? "Política de Privacidade do FIXAR." : "Termos de Uso do FIXAR."); }, [privacy]);
  return <main className="legal-page"><header className="legal-header"><a className="legal-brand" href="/"><span>⌁</span><strong>fixar</strong></a><nav><a href="/privacidade" aria-current={privacy ? "page" : undefined}>Privacidade</a><a href="/termos" aria-current={!privacy ? "page" : undefined}>Termos</a></nav></header><article className="legal-card"><p className="legal-eyebrow">FIXAR · DOCUMENTO PÚBLICO</p><h1>{privacy ? "Política de Privacidade" : "Termos de Uso"}</h1><p className="legal-lead">{privacy ? "Como o FIXAR trata dados para operar sua plataforma de manutenção e identificação de equipamentos." : "Regras simples para usar o FIXAR com segurança na rotina da sua empresa."}</p><p className="legal-date">Última atualização: {updated}</p><div className="legal-body">{privacy ? <PrivacyContent /> : <TermsContent />}</div></article><footer className="legal-footer"><span>© FIXAR</span><a href="/privacidade">Política de Privacidade</a><a href="/termos">Termos de Uso</a></footer></main>;
}

export function AccountDeletionPage() { useEffect(() => { document.title = "Excluir conta | FIXAR"; }, []); return <main className="legal-page"><header className="legal-header"><a className="legal-brand" href="/"><span>⌁</span><strong>fixar</strong></a><nav><a href="/privacidade">Privacidade</a><a href="/termos">Termos</a></nav></header><article className="legal-card"><p className="legal-eyebrow">FIXAR · EXCLUSÃO DE CONTA</p><h1>Solicitar exclusão da conta</h1><p className="legal-lead">O FIXAR oferece um fluxo seguro dentro do aplicativo para excluir sua conta sem apagar dados compartilhados da empresa por engano.</p><p className="legal-date">Última atualização: {updated}</p><div className="legal-body"><Section title="Como fazer"><ol><li>Abra o aplicativo FIXAR e entre na conta.</li><li>Acesse <strong>Dados da empresa</strong> e toque em <strong>Excluir minha conta</strong>.</li><li>Leia o impacto, digite <strong>EXCLUIR</strong> e confirme.</li><li>O servidor verifica sua sessão e sua função antes de concluir ou registrar a solicitação.</li></ol></Section><Section title="O que é excluído"><p>Para membros que não são proprietários, a conta, a associação à empresa e os dados locais privados são removidos. A exclusão não apaga clientes, equipamentos, QR Codes, manutenções, relatórios ou dados de outros membros da organização.</p></Section><Section title="Quando você é proprietário"><p>Uma conta proprietária de empresa com dados não é apagada automaticamente. O pedido fica registrado para revisão segura da organização, evitando deixar dados compartilhados órfãos ou apagar o histórico da empresa sem confirmação apropriada.</p></Section><Section title="Assinaturas"><p>Excluir a conta não cancela cobranças da Google Play ou App Store. Cancele ou gerencie a assinatura na loja correspondente; o FIXAR não armazena dados completos de cartão.</p></Section><Section title="Acesso e privacidade"><p>A página é pública para explicar o processo, mas a exclusão efetiva exige sessão autenticada no aplicativo. Consulte a <a href="/privacidade">Política de Privacidade</a> e os <a href="/termos">Termos de Uso</a>.</p></Section></div></article><footer className="legal-footer"><a href="/privacidade">Política de Privacidade</a><a href="/termos">Termos de Uso</a></footer></main>; }

function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h2>{title}</h2>{children}</section>; }
function PrivacyContent() { return <>
  <Section title="1. Quem somos"><p>O FIXAR é uma plataforma SaaS para empresas e profissionais que registram clientes, equipamentos, serviços e manutenções. Esta política explica o tratamento de dados quando você usa o aplicativo ou as páginas públicas do serviço.</p></Section>
  <Section title="2. Dados tratados"><p>Podem ser tratados dados de conta (nome, e-mail e identificador), dados da organização (nome, documento quando informado, telefone, e-mail, endereço e logomarca), e dados inseridos pela organização sobre clientes e equipamentos. Registros de manutenção podem conter problemas relatados, diagnósticos, checklists, medições, serviços, materiais, valores, recomendações, observações, datas e assinaturas manuscritas.</p><p>Também tratamos dados técnicos necessários à operação, como identificadores da sessão, estado de sincronização e informações técnicas da assinatura. O FIXAR não recebe o número completo do cartão: compras são processadas pela Google Play ou App Store, que possuem suas próprias políticas.</p></Section>
  <Section title="3. Para que usamos os dados"><ul><li>criar e autenticar contas e organizar permissões;</li><li>operar cadastros, manutenções, relatórios, orçamentos e QR Codes;</li><li>sincronizar dados e permitir manutenção individual temporariamente sem conexão;</li><li>gerenciar assinaturas, segurança, prevenção de abuso e suporte;</li><li>cumprir obrigações legais quando aplicável.</li></ul></Section>
  <Section title="4. QR público"><p>A organização pode disponibilizar um QR público de equipamento. Sem login, a página pode mostrar a empresa responsável, logomarca quando autorizada pelo plano, identificação e características do equipamento, manutenção anterior/próxima, histórico resumido e contato operacional. Não são destinados à página pública endereço completo de cliente, valores, diagnóstico detalhado ou assinaturas. A organização é responsável por decidir quando usar esse recurso.</p></Section>
  <Section title="5. Onde os dados ficam e com quem compartilhamos"><p>O FIXAR usa provedores de infraestrutura e armazenamento em nuvem, incluindo Supabase/PostgreSQL, para operar o serviço. Dados técnicos de compra podem ser processados pela Google Play e pela App Store para validação, prevenção de fraude e estado da assinatura. Não vendemos dados pessoais nem os compartilhamos para publicidade comportamental. Podemos processar dados com fornecedores técnicos necessários e atender determinações legais.</p></Section>
  <Section title="6. Retenção e segurança"><p>Mantemos dados enquanto necessários à prestação do serviço, ao relacionamento com a organização, à segurança e às obrigações legais. Downgrade não apaga automaticamente os dados; recursos e histórico podem ficar sujeitos aos limites do plano. Usamos autenticação, controle de acesso, isolamento por organização, comunicação segura e medidas administrativas razoáveis. Nenhum serviço pode garantir segurança absoluta.</p></Section>
  <Section title="7. Seus direitos e responsabilidades"><p>Você pode solicitar confirmação, acesso, correção e, quando aplicável, exclusão ou informação sobre o tratamento, observadas as obrigações legais e os dados necessários à conta. A organização usuária é responsável por ter base legal e autorização adequada para inserir dados de seus clientes no FIXAR e por usar assinaturas manuscritas de forma legítima.</p><p>Para solicitações, use o canal de suporte disponibilizado no produto ou no site do FIXAR. O endereço de contato operacional deve ser conferido na publicação da loja.</p></Section>
  <Section title="8. Crianças, alterações e exclusão"><p>O FIXAR é uma ferramenta profissional e não é direcionado a crianças. Esta política pode ser atualizada; a data acima será alterada quando houver revisão relevante. Consulte o <a href="/excluir-conta">fluxo de exclusão de conta</a> para ver as etapas, os dados compartilhados preservados e o tratamento de contas proprietárias.</p></Section>
  <p className="legal-note">Esta política descreve o funcionamento atual do FIXAR e pode ser complementada por informações específicas da organização usuária.</p>
</>; }
function TermsContent() { return <>
  <Section title="1. O serviço"><p>O FIXAR fornece software como serviço para organizar clientes, equipamentos, QR Codes, manutenções, orçamentos e relatórios. O usuário precisa de uma conta e de autorização na organização correspondente.</p></Section>
  <Section title="2. Conta e organização"><p>Informe dados corretos, proteja suas credenciais e use somente organizações às quais você tem autorização. A empresa usuária administra os dados que cadastra e as permissões que concede aos seus membros.</p></Section>
  <Section title="3. Planos e assinaturas"><p>Os planos atuais são Grátis, Professional e Team. Recursos e limites aparecem no aplicativo e podem ser atualizados. Como referência, Professional é R$ 39,90/mês e Team R$ 79,90/mês; o preço final, impostos e moeda são os exibidos pela loja. Assinaturas móveis são processadas pela Google Play ou App Store, e cancelamentos e cobranças seguem as regras da plataforma correspondente.</p><p>O cancelamento não apaga automaticamente dados. Ao terminar o período pago, a organização pode retornar ao Free e novos usos ficam sujeitos aos limites desse plano, preservando dados conforme a política do serviço.</p></Section>
  <Section title="4. Uso aceitável"><p>Não use o FIXAR para fins ilegais, fraude, acesso não autorizado, tentativa de burlar limites, exploração abusiva, conteúdo ilícito ou interferência na infraestrutura. Podemos limitar ou suspender acesso quando necessário para segurança, cumprimento legal ou proteção do serviço.</p></Section>
  <Section title="5. Dados, QR e assinaturas"><p>A empresa usuária continua responsável pela legitimidade dos dados de seus clientes e pela finalidade das assinaturas coletadas. QR público e informações exibidas nele dependem da escolha da organização. Relatórios são gerados a partir dos dados fornecidos e não constituem, por si só, laudo, certificação, garantia técnica ou conformidade regulatória.</p></Section>
  <Section title="6. Disponibilidade e responsabilidade"><p>O serviço pode passar por manutenção, indisponibilidade, falhas de internet ou falhas de terceiros. O armazenamento offline é específico para determinados registros e não significa que o aplicativo inteiro funcione sem conexão. O FIXAR é uma ferramenta; decisões técnicas, serviços executados e relações com clientes finais continuam sob responsabilidade da empresa usuária.</p></Section>
  <Section title="7. Propriedade e encerramento"><p>Marca, software, interface e conteúdo próprio do FIXAR permanecem protegidos. Os dados inseridos continuam relacionados à organização usuária, conforme a legislação aplicável. Podemos encerrar ou suspender contas em caso de violação destes termos, obrigação legal ou risco ao serviço, preservando dados quando exigido.</p></Section>
  <Section title="8. Alterações e contato"><p>Podemos atualizar estes termos para refletir mudanças no serviço ou na legislação. A data da última atualização aparece no início. Para dúvidas, use o canal de suporte disponibilizado no produto ou no site do FIXAR; confirme o contato operacional informado no momento da publicação.</p></Section>
  <p className="legal-note">Leia também a <a href="/privacidade">Política de Privacidade</a>.</p>
</>; }
