import { applyVerifiedSubscription, bearer, json, PRODUCT_PLANS, admin, requireOwner } from "../_shared/billing.ts";

const base64url = (value: string) => value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4);
async function googleAccessToken() {
  const raw = Deno.env.get("GOOGLE_PLAY_SERVICE_ACCOUNT_JSON"); if (!raw) throw new Error("GOOGLE_NOT_CONFIGURED");
  const account = JSON.parse(raw); const now = Math.floor(Date.now() / 1000); const header = base64url(btoa(JSON.stringify({ alg: "RS256", typ: "JWT" }))); const payload = base64url(btoa(JSON.stringify({ iss: account.client_email, scope: "https://www.googleapis.com/auth/androidpublisher", aud: "https://oauth2.googleapis.com/token", iat: now, exp: now + 3600 })));
  const pem = account.private_key.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g, ""); const key = await crypto.subtle.importKey("pkcs8", Uint8Array.from(atob(base64url(pem)), (c) => c.charCodeAt(0)), { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]); const signature = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(`${header}.${payload}`));
  const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer", assertion: `${header}.${payload}.${base64url(btoa(String.fromCharCode(...new Uint8Array(signature))))}` }) });
  if (!response.ok) throw new Error("GOOGLE_AUTH_FAILED"); return (await response.json()).access_token as string;
}
export async function verifyGoogle(productId: string, token: string) {
  const packageName = Deno.env.get("GOOGLE_PLAY_PACKAGE_NAME"); if (!packageName) throw new Error("GOOGLE_NOT_CONFIGURED"); const access = await googleAccessToken(); const response = await fetch(`https://androidpublisher.googleapis.com/androidpublisher/v3/applications/${encodeURIComponent(packageName)}/purchases/subscriptionsv2/tokens/${encodeURIComponent(token)}`, { headers: { authorization: `Bearer ${access}` } }); if (!response.ok) throw new Error("GOOGLE_PURCHASE_INVALID"); const body = await response.json(); const line = body.lineItems?.find((item: any) => item.productId === productId); if (!line) throw new Error("PRODUCT_MISMATCH"); const state = body.subscriptionState; const providerStatus = state === "SUBSCRIPTION_STATE_ACTIVE" ? "active" : state === "SUBSCRIPTION_STATE_IN_GRACE_PERIOD" ? "past_due" : state === "SUBSCRIPTION_STATE_ON_HOLD" ? "past_due" : state === "SUBSCRIPTION_STATE_CANCELED" ? "canceled" : state === "SUBSCRIPTION_STATE_EXPIRED" ? "canceled" : "incomplete"; if (providerStatus === "incomplete") throw new Error("PURCHASE_NOT_ACTIVE"); return { providerSubscriptionId: body.latestOrderId ?? null, periodEnd: line.expiryTime ?? null, autoRenew: line.autoRenewingPlan?.autoRenewEnabled ?? null, providerStatus } as const;
}
export async function verifyApple(productId: string, token: string) {
  const key = Deno.env.get("APPLE_APP_STORE_SERVER_API_KEY"); const keyId = Deno.env.get("APPLE_KEY_ID"); const issuer = Deno.env.get("APPLE_ISSUER_ID"); const bundle = Deno.env.get("APPLE_BUNDLE_ID"); const roots = Deno.env.get("APPLE_ROOT_CA_BASE64"); if (!key || !keyId || !issuer || !bundle || !roots) throw new Error("APPLE_NOT_CONFIGURED");
  const { AppStoreServerAPIClient, Environment, SignedDataVerifier } = await import("npm:@apple/app-store-server-library@3.1.0"); const environment = Deno.env.get("APPLE_ENVIRONMENT") === "sandbox" ? Environment.SANDBOX : Environment.PRODUCTION; const verifier = new SignedDataVerifier(roots.split(",").map((root) => Buffer.from(root, "base64")), true, environment, bundle, Deno.env.get("APPLE_APP_ID") ? Number(Deno.env.get("APPLE_APP_ID")) : undefined); const transaction = await verifier.verifyAndDecodeTransaction(token); if (transaction.bundleId !== bundle || transaction.productId !== productId || !transaction.originalTransactionId) throw new Error("APPLE_PURCHASE_INVALID"); const client = new AppStoreServerAPIClient(key, keyId, issuer, bundle, environment); const statuses = await client.getAllSubscriptionStatuses(transaction.originalTransactionId); const last = statuses.data?.flatMap((group: any) => group.lastTransactions ?? []).find((item: any) => item.signedTransactionInfo); if (!last) throw new Error("APPLE_PURCHASE_NOT_ACTIVE"); const latest = await verifier.verifyAndDecodeTransaction(last.signedTransactionInfo); const renewal = last.signedRenewalInfo ? await verifier.verifyAndDecodeRenewalInfo(last.signedRenewalInfo) : null; const revoked = Boolean(latest.revocationDate); return { providerSubscriptionId: latest.transactionId, originalTransactionId: latest.originalTransactionId, periodStart: latest.purchaseDate ? new Date(latest.purchaseDate).toISOString() : null, periodEnd: latest.expiresDate ? new Date(latest.expiresDate).toISOString() : null, autoRenew: renewal?.autoRenewStatus === 1, providerStatus: revoked || (latest.expiresDate && latest.expiresDate < Date.now()) ? "canceled" : "active" } as const;
}

Deno.serve(async (request) => { if (request.method !== "POST") return json({ message: "Method not allowed" }, 405); try { const body = await request.json(); const planCode = body.plan_code as "professional" | "team"; if (!body.organization_id || !PRODUCT_PLANS[body.product_id] || PRODUCT_PLANS[body.product_id] !== planCode) throw new Error("PRODUCT_MISMATCH"); await requireOwner(request, body.organization_id); if (body.provider !== "google_play" && body.provider !== "app_store") throw new Error("PROVIDER_INVALID"); if (body.provider === "google_play" && !body.purchase_token) throw new Error("PURCHASE_TOKEN_REQUIRED"); if (body.provider === "app_store" && !body.signed_transaction_info) throw new Error("TRANSACTION_REQUIRED"); const verified = body.provider === "google_play" ? await verifyGoogle(body.product_id, body.purchase_token) : await verifyApple(body.product_id, body.signed_transaction_info); const result = await applyVerifiedSubscription({ organizationId: body.organization_id, provider: body.provider, planCode, productId: body.product_id, providerSubscriptionId: verified.providerSubscriptionId, purchaseToken: body.provider === "google_play" ? body.purchase_token : body.signed_transaction_info, originalTransactionId: verified.originalTransactionId ?? null, periodStart: verified.periodStart ?? null, periodEnd: verified.periodEnd ?? null, autoRenew: verified.autoRenew, providerStatus: verified.providerStatus, environment: body.provider === "app_store" && Deno.env.get("APPLE_ENVIRONMENT") === "sandbox" ? "sandbox" : "production" }); return json({ verified: true, ...result }); } catch (error) { const code = error instanceof Error ? error.message : "VERIFY_FAILED"; const messages: Record<string, string> = { AUTH_REQUIRED: "Sessão inválida.", OWNER_REQUIRED: "Somente o proprietário pode contratar um plano.", PURCHASE_ALREADY_LINKED: "Esta assinatura já está vinculada a outra empresa.", PRODUCT_MISMATCH: "O produto da loja não corresponde ao plano escolhido.", PURCHASE_NOT_ACTIVE: "Sua compra ainda não foi confirmada pela loja.", GOOGLE_NOT_CONFIGURED: "Compras não estão disponíveis neste ambiente.", APPLE_NOT_CONFIGURED: "Compras não estão disponíveis neste ambiente." }; return json({ verified: false, code, message: messages[code] ?? "Não foi possível confirmar sua assinatura." }, code === "AUTH_REQUIRED" || code === "OWNER_REQUIRED" ? 403 : 400); } });
