import { Alert, ScrollView, Text, View } from "react-native";
import { Check, Star } from "lucide-react-native";
import { useTheme } from "styled-components/native";
import { Header } from "../../components/Header";
import { Button, Card, ErrorState, Spinner } from "../../design-system";
import { formatCommercialPrice } from "../../domain/commercialPlans";
import { useCommercial } from "../../commercial/CommercialContext";

export function Plans(){const theme=useTheme();const {plans,entitlements,loading,error,refresh}=useCommercial();if(loading&&!plans.length)return <View style={{flex:1,backgroundColor:theme.colors.background}}><Header title="Planos" icons/><Spinner/></View>;if(error&&!plans.length)return <View style={{flex:1,backgroundColor:theme.colors.background}}><Header title="Planos" icons/><ErrorState title="Não foi possível carregar os planos" description={error} onRetry={refresh}/></View>;return <View style={{flex:1,backgroundColor:theme.colors.background}}><Header title="Planos" icons/><ScrollView contentContainerStyle={{padding:16,gap:14}}>{plans.map(plan=>{const recommended=plan.code==="professional";const current=plan.code===entitlements?.planCode;const facts=[`${plan.limits.users} usuário${plan.limits.users===1?"":"s"}`,plan.limits.customers===null?"Clientes e equipamentos ilimitados":`${plan.limits.customers} clientes · ${plan.limits.equipment} equipamentos`,`${plan.limits.qr_codes} QR Codes`,plan.limits.work_orders_monthly===null?"OS e orçamentos ilimitados":`${plan.limits.work_orders_monthly} OS · ${plan.limits.quotes_monthly} orçamentos`,plan.features.full_history?"Histórico completo":`${plan.history_days} dias de histórico`,plan.features.batch_orders?"Manutenção em lote":"Sem manutenção em lote",plan.features.custom_branding?"Branding da empresa":"Identidade FIXAR nos documentos"];return <Card key={plan.code}><View style={{gap:12}}>{recommended&&<View style={{flexDirection:"row",gap:6,alignItems:"center"}}><Star size={15} color={theme.colors.primary}/><Text style={{color:theme.colors.primary,fontFamily:theme.fonts.semibold}}>Mais recomendado</Text></View>}<Text style={{fontFamily:theme.fonts.semibold,fontSize:21,color:theme.colors.foreground}}>{plan.display_name}</Text><Text style={{fontFamily:theme.fonts.bold,fontSize:24,color:theme.colors.foreground}}>{formatCommercialPrice(plan.price_cents,plan.billing_cycle)}</Text>{facts.map(x=><View key={x} style={{flexDirection:"row",gap:8}}><Check size={16} color={theme.colors.primary}/><Text style={{flex:1,color:theme.colors.muted}}>{x}</Text></View>)}<Button label={current?"Plano atual":"Tenho interesse"} disabled={current} variant={recommended?"primary":"secondary"} onPress={()=>Alert.alert("Contratação pelo atendimento","A alteração de plano é concluída pelo atendimento ou pelo administrador global. Nenhuma cobrança foi realizada.")}/></View></Card>})}</ScrollView></View>}
