import moment from "moment";
import { Customer, Device, Part, Service } from "../../types/data";
import { escapeHtml, htmlDocument, ReportOrganization } from "./reportDocument";

const money = (value: string | number) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export const generateHtml = (customer: Customer, device: Device, parts: Part[], services: Service[], comments: string, total: string | number, date: string, company: ReportOrganization, technician?: string) => htmlDocument(company, `
  <section class="report-heading"><div><h2>Relatório de manutenção</h2><p>Atendimento em ${moment(date).format("DD/MM/YYYY")}</p></div><span class="badge">${escapeHtml(device.reference)}</span></section>
  <section class="section"><div class="section-title">Cliente</div><div class="grid"><div class="field"><span class="label">Nome</span><span class="value">${escapeHtml(customer.name)}</span></div><div class="field"><span class="label">Documento</span><span class="value">${escapeHtml(customer.document || "—")}</span></div><div class="field"><span class="label">Telefone</span><span class="value">${escapeHtml(customer.phone || "—")}</span></div><div class="field"><span class="label">Endereço</span><span class="value">${escapeHtml(customer.address || "—")}</span></div></div></section>
  <section class="section"><div class="section-title">Equipamento</div><div class="grid"><div class="field"><span class="label">Referência</span><span class="value">${escapeHtml(device.reference)}</span></div><div class="field"><span class="label">Ambiente</span><span class="value">${escapeHtml(device.location || "—")}</span></div><div class="field"><span class="label">Marca</span><span class="value">${escapeHtml(device.brand || "—")}</span></div><div class="field"><span class="label">Modelo</span><span class="value">${escapeHtml(device.model || "—")}</span></div></div></section>
  <section class="section"><div class="section-title">Serviços executados</div><ul class="items">${services.length ? services.map((service) => `<li><span class="value">${escapeHtml(service.name)}</span>${service.description ? `<br><span class="muted">${escapeHtml(service.description)}</span>` : ""}</li>`).join("") : "<li>Nenhum serviço registrado</li>"}</ul></section>
  <section class="section"><div class="section-title">Fechamento</div><div class="grid"><div class="field"><span class="label">Peças e materiais</span><span class="value">${parts.length ? parts.map((part) => escapeHtml(part.name)).join(", ") : "Nenhum"}</span></div><div class="field"><span class="label">Valor total</span><span class="value">${money(total)}</span></div><div class="field full"><span class="label">Observações técnicas</span><span class="value">${escapeHtml(comments || "Sem observações")}</span></div>${technician ? `<div class="field full"><span class="label">Responsável técnico</span><span class="value">${escapeHtml(technician)}</span></div>` : ""}</div></section>
  <div class="signatures"><div class="signature">Responsável técnico</div><div class="signature">Cliente / responsável</div></div>`, "Relatório de manutenção");
