import { admin, json, PRODUCT_PLANS } from "../_shared/billing.ts";

const b64urlToBytes = (value: string) => Uint8Array.from(atob(value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4)), (c) => c.charCodeAt(0));

async function googleAccessToken() {
  const raw = Deno.env.get("GOOGLE_PLAY_SERVICE_ACCOUNT_JSON"); if (!raw) throw new Error("NOT_CONFIGURED");
  const account = JSON.parse(raw); const encode = (value: string) => btoa(value).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); const now = Math.floor(Date.now() / 1000); const header = encode(JSON.stringify({ alg: "RS256", typ: "JWT" })); const payload = encode(JSON.stringify({ iss: account.client_email, scope: "https://www.googleapis.com/auth/androidpublisher", aud: "https://oauth2.googleapis.com/token", iat: now, exp: now + 3600 })); const pem = account.private_key.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g, ""); const key = await crypto.subtle.importKey("pkcs8", b64urlToBytes(pem), { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]); const signature = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(`${header}.${payload}`)); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer", assertion: `${header}.${payload}.${encode(String.fromCharCode(...new Uint8Array(signature)))}` }) }); if (!response.ok) throw new Error("AUTH_FAILED"); return (await response.json()).access_token as string;
}

Deno.serve(async (request) => {
  if (request.method !== "POST") return json({ message: "Method not allowed" }, 405);
  try {
    const auth = request.headers.get("authorization")?.replace(/^Bearer\s+/i, ""); const audience = Deno.env.get("GOOGLE_PUBSUB_AUDIENCE"); if (!auth || !audience) throw new Error("UNAUTHORIZED"); const tokenInfo = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(auth)}`); const claims = tokenInfo.ok ? await tokenInfo.json() : null; if (!claims || claims.aud !== audience) throw new Error("UNAUTHORIZED");
    const envelope = await request.json(); const message = envelope.message ?? {}; const eventId = String(message.messageId ?? ""); const raw = message.data; if (!raw) throw new Error("INVALID_NOTIFICATION"); const event = JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(raw), (c) => c.charCodeAt(0)))); const token = event.subscriptionNotification?.purchaseToken; if (!token) return json({ received: true }); const client = admin();
    if (eventId) { const inserted = await client.from("billing_webhook_events").insert({ provider: "google_play", external_event_id: eventId, payload_hash: eventId }); if (inserted.error?.code === "23505") return json({ received: true, duplicate: true }); }
    const { data: subscription } = await client.from("organization_subscriptions").select("organization_id, provider_product_id, subscription_status").eq("provider", "google_play").eq("provider_purchase_token", token).maybeSingle(); if (!subscription || !PRODUCT_PLANS[subscription.provider_product_id]) return json({ received: true });
    const packageName = Deno.env.get("GOOGLE_PLAY_PACKAGE_NAME"); if (!packageName) throw new Error("NOT_CONFIGURED"); const response = await fetch(`https://androidpublisher.googleapis.com/androidpublisher/v3/applications/${encodeURIComponent(packageName)}/purchases/subscriptionsv2/tokens/${encodeURIComponent(token)}`, { headers: { authorization: `Bearer ${await googleAccessToken()}` } }); if (!response.ok) throw new Error("VERIFY_FAILED"); const state = (await response.json()).subscriptionState; const status = state === "SUBSCRIPTION_STATE_ACTIVE" ? "active" : state === "SUBSCRIPTION_STATE_IN_GRACE_PERIOD" || state === "SUBSCRIPTION_STATE_ON_HOLD" ? "past_due" : "canceled"; if (subscription.subscription_status !== status) await client.from("organization_subscriptions").update({ subscription_status: status, last_verified_at: new Date().toISOString() }).eq("organization_id", subscription.organization_id).eq("provider_purchase_token", token); return json({ received: true });
  } catch { return json({ message: "Notification could not be verified" }, 400); }
});
